stages:
  - lint
  - deploy


variables:
  HELM_CHART_TAG: 0.1.0
  OKD_NAMESPACE: db_service
  HOST: https://api.okd.eu-central-1.cloud..app:6443

helm_lint:
  stage: lint
  image:
    name: alpine/helm:3.3.4
    entrypoint: ["/bin/sh", "-c"]

  script:
    - |
      helm lint .

deploy:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - helm upgrage --install  --kube-token ${OKD4_TOKEN} --kube-apiserver ${HOST} --namespace ${OKD_NAMESPACE}