apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.endpoints.name }}
  labels:
    app: {{ .Values.endpoints.app }}
subsets:
  - addresses:
      - ip: {{ .Values.endpoints.ip }}
    ports:
      - port: {{ .Values.endpoints.mysqlExporterPort }}
        name: {{ .Values.endpoints.mysqlExporterPortName }}
      - port: {{ .Values.endpoints.netdataPort }}
        name: {{ .Values.endpoints.netdataPortName }}