{{- range .Values.db  }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}-monitor
  labels:
    app: {{ .name }}-service
spec:
  selector:
    matchLabels:
      app: {{ .name }}-service
  endpoints:
    - port: {{ .portName }}-mysql-exporter
      interval: 1m
      path: /metrics
    - port: {{ .portName }}-netdata
      interval: 1m
      path: /api/v1/allmetrics?format=prometheus_all_hosts&timestamps=no
    - port: {{ .portName }}-netdata
      interval: 1m
      path: /api/v1/allmetrics?format=prometheus_all_hosts&timestamps=no
{{- end }}